version: "3.7"
services:

  front:
    image: rottiakash/resnal-angular-base:v2
    ports:
      - "80:80"
  back:
    image: rottiakash/resnal:v2
    volumes:
      - ./:/app
    ports:
        - "1216:80"